# tony server
alias tony="ssh root@$TONY"
# listen ports
alias listen="lsof -i -P -n | grep LISTEN"
# tmux alias
alias t="tmux -u"
alias ts="tmux -u new-session -s"
alias ta="tmux -u attach -t"
alias tl="tmux ls"
# git alias
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gc="git commit --signoff --message"
alias gcb="git checkout -b"
alias gl="git log --graph --pretty --stat"
alias gpl="git pull"
alias gps="git push -u"
alias gs="git status --short --branch"
