# tony server
alias tony="ssh root@$TONY"
# listen ports
alias listen="lsof -i -P -n | grep LISTEN"
# tmux alias
alias tmux="tmux -u"
# git alias
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch"
alias gbc="git checkout -b"
alias gbs"git checkout"
alias gc="git commit --message"
alias gl="git log --graph --pretty --stat"
alias gpl="git pull"
alias gps="git push -u"
alias gs="git status --short --branch"
